#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""用户学习工具加载器（C1 半自动）。

目录结构::

    {config_dir}/user_tools/<tool_name>.py        # 工具源码
    {config_dir}/user_tools/<tool_name>.meta.json # 元数据

每个 .py 文件必须定义一个用 ``@tool`` 装饰的函数（可直接 from
maxagent.tools import tool）。本模块在启动时扫盘，按文件 import 模块，
触发装饰器把工具注册进全局 registry。

为什么不让生成的工具自动 dangerous=True？
- 学习而来的工具本质是动态加载用户机器上的 Python 代码，行为未知，
  必须经过用户审批（C1 方案）。审批通过后我们仍然给它打 dangerous 标
  记，意味着每次调用还会再问一次（可在设置里关闭）。

加载流程::

    list_user_tools()      # 扫描 user_tools/ 列出所有
    register_user_tool(name, code, schema, description, ...)
                           # 落盘 .py + .meta.json
    load_user_tools()      # 一次性 import 所有 .py 触发注册
    reload_user_tool(name) # 单个工具的热重载

学习工具的元数据 (.meta.json)::

    {
      "name": "cleanup_temp_objects",
      "description": "...",
      "created_at": 1700000000.0,
      "use_count": 0,
      "source_session_sid": "abc12345",
      "approved_by_user": true
    }
"""

from __future__ import absolute_import
from __future__ import print_function

import importlib
import importlib.util
import json
import os
import re
import sys
import time
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from .config import get_config_dir


USER_TOOLS_DIRNAME = 'user_tools'
META_SUFFIX = '.meta.json'

# 工具名校验：合法的 Python 标识符 + 长度限制
_NAME_RE = re.compile(r'^[a-z][a-z0-9_]{1,40}$')

# 单个工具源码最大字节数（防止恶意 LLM 写出超长代码）
MAX_CODE_BYTES = 32 * 1024


def get_user_tools_dir():
    base = get_config_dir()
    path = os.path.join(base, USER_TOOLS_DIRNAME)
    if not os.path.isdir(path):
        os.makedirs(path)
    # 确保有 __init__.py，方便 import
    init_py = os.path.join(path, '__init__.py')
    if not os.path.exists(init_py):
        with open(init_py, 'w', encoding='utf-8') as fh:
            fh.write('# auto-generated\n')
    return path


def _tool_py_path(name, base_dir=None):
    base = base_dir or get_user_tools_dir()
    return os.path.join(base, name + '.py')


def _tool_meta_path(name, base_dir=None):
    base = base_dir or get_user_tools_dir()
    return os.path.join(base, name + META_SUFFIX)


def validate_name(name):
    # type: (str) -> None
    """校验工具名，非法时抛 ValueError。"""
    if not name or not _NAME_RE.match(name):
        raise ValueError(
            '工具名只能小写字母 + 数字 + 下划线，必须以字母开头，'
            '长度 2-41，收到: {!r}'.format(name),
        )
    # 不允许覆盖内置工具
    from .tools.registry import get_tool as _g
    if _g(name) is not None:
        # 但允许 reload 已经存在的 user tool（同名覆盖）
        meta_path = _tool_meta_path(name)
        if not os.path.exists(meta_path):
            raise ValueError('工具名与内置工具冲突: {}'.format(name))


def validate_code(code):
    # type: (str) -> None
    """对 LLM 生成的代码做基础静态检查（语法 + 大小）。

    注意：这不是安全沙箱，仅过滤明显异常。真正的"是否要执行"决策
    由 UI 弹窗交给用户。
    """
    if not code or not code.strip():
        raise ValueError('代码不能为空')
    encoded = code.encode('utf-8')
    if len(encoded) > MAX_CODE_BYTES:
        raise ValueError(
            '代码超出最大长度 {} 字节: {}'.format(
                MAX_CODE_BYTES, len(encoded),
            ),
        )
    # 语法检查
    try:
        compile(code, '<learned_tool>', 'exec')
    except SyntaxError as exc:
        raise ValueError('代码语法错误: {}'.format(exc))


def write_tool(name, code, meta):
    # type: (str, str, Dict[str, Any]) -> str
    """落盘单个工具的源码 + 元数据，返回 .py 路径。"""
    validate_name(name)
    validate_code(code)
    base = get_user_tools_dir()
    py_path = _tool_py_path(name, base)
    meta_path = _tool_meta_path(name, base)

    # 头部加注释，方便用户在文件浏览器看到这是 agent 生成的
    header = (
        '#!/usr/bin/env python3\n'
        '# -*- coding: utf-8 -*-\n'
        '"""auto-generated by MaxAgent.\n\n'
        'Tool name: {name}\n'
        'Approved at: {ts}\n"""\n\n'
    ).format(name=name, ts=time.strftime('%Y-%m-%d %H:%M:%S'))

    # 自动确保 import 语句到位（用户审批界面里看到的代码可以省略 import，
    # 我们这里强制注入；如果用户已经写了，重复 import 也是合法的）
    if 'from maxagent.tools import tool' not in code \
            and 'from maxagent.tools.registry import tool' not in code:
        header += 'from maxagent.tools.registry import tool\n\n'

    full = header + code if not code.startswith('#!') else code

    tmp = py_path + '.tmp'
    with open(tmp, 'w', encoding='utf-8') as fh:
        fh.write(full)
    if os.path.exists(py_path):
        os.replace(tmp, py_path)
    else:
        os.rename(tmp, py_path)

    # 写 meta
    full_meta = dict(meta or {})
    full_meta.setdefault('name', name)
    full_meta.setdefault('created_at', time.time())
    full_meta.setdefault('use_count', 0)
    full_meta.setdefault('approved_by_user', True)
    tmp_meta = meta_path + '.tmp'
    with open(tmp_meta, 'w', encoding='utf-8') as fh:
        json.dump(full_meta, fh, ensure_ascii=False, indent=2)
    if os.path.exists(meta_path):
        os.replace(tmp_meta, meta_path)
    else:
        os.rename(tmp_meta, meta_path)
    return py_path


def list_user_tools(include_meta=True):
    # type: (bool) -> List[Dict[str, Any]]
    """列出所有用户学习工具的元数据 + 路径。"""
    base = get_user_tools_dir()
    out = []
    for fname in sorted(os.listdir(base)):
        if not fname.endswith('.py') or fname == '__init__.py':
            continue
        name = fname[:-3]
        py_path = os.path.join(base, fname)
        meta_path = _tool_meta_path(name, base)
        item = {
            'name': name,
            'py_path': py_path,
            'has_meta': os.path.exists(meta_path),
        }
        if include_meta and item['has_meta']:
            try:
                with open(meta_path, 'r', encoding='utf-8') as fh:
                    item['meta'] = json.load(fh)
            except (OSError, ValueError):
                item['meta'] = {}
        out.append(item)
    return out


def delete_user_tool(name):
    # type: (str) -> bool
    """删除指定的学习工具（源码 + 元数据 + 注册表条目）。"""
    base = get_user_tools_dir()
    py_path = _tool_py_path(name, base)
    meta_path = _tool_meta_path(name, base)
    found = False
    for p in (py_path, meta_path):
        if os.path.exists(p):
            try:
                os.remove(p)
                found = True
            except OSError as exc:
                print('[maxagent] 删除 {} 失败: {}'.format(p, exc))
    # 从 registry 移除
    from .tools.registry import _REGISTRY
    if name in _REGISTRY:
        del _REGISTRY[name]
        found = True
    return found


def _import_tool_module(py_path, force_reload=False):
    """按完整路径 import 单个 .py 文件，触发其内部 @tool 装饰器注册。"""
    name = os.path.splitext(os.path.basename(py_path))[0]
    mod_name = '_maxagent_user_tool_' + name
    try:
        if force_reload and mod_name in sys.modules:
            # 先把旧模块产生的工具从 registry 拿掉，避免 ValueError 重名
            from .tools.registry import _REGISTRY
            if name in _REGISTRY:
                del _REGISTRY[name]
            del sys.modules[mod_name]

        spec = importlib.util.spec_from_file_location(mod_name, py_path)
        if spec is None or spec.loader is None:
            raise ImportError('无法 spec_from_file_location: ' + py_path)
        mod = importlib.util.module_from_spec(spec)
        sys.modules[mod_name] = mod
        spec.loader.exec_module(mod)
        return mod
    except Exception as exc:  # pylint: disable=broad-except
        # 加载失败：从 sys.modules 清掉残留，避免影响下次重试
        sys.modules.pop(mod_name, None)
        raise


def load_user_tools(stop_on_error=False):
    # type: (bool) -> Dict[str, Any]
    """启动时扫盘并 import 所有 user tools。

    :returns: ``{"loaded": [...], "errors": {name: error_msg, ...}}``
    """
    base = get_user_tools_dir()
    loaded = []
    errors = {}
    for fname in sorted(os.listdir(base)):
        if not fname.endswith('.py') or fname == '__init__.py':
            continue
        name = fname[:-3]
        py_path = os.path.join(base, fname)
        try:
            _import_tool_module(py_path, force_reload=True)
            loaded.append(name)
        except Exception as exc:  # pylint: disable=broad-except
            errors[name] = '{}: {}'.format(type(exc).__name__, exc)
            if stop_on_error:
                break
    return {'loaded': loaded, 'errors': errors}


def reload_user_tool(name):
    # type: (str) -> None
    """单个工具的热重载（用户审批通过后立即生效）。"""
    py_path = _tool_py_path(name)
    if not os.path.exists(py_path):
        raise FileNotFoundError(py_path)
    _import_tool_module(py_path, force_reload=True)


__all__ = [
    'get_user_tools_dir',
    'list_user_tools',
    'delete_user_tool',
    'load_user_tools',
    'reload_user_tool',
    'write_tool',
    'validate_name',
    'validate_code',
    'MAX_CODE_BYTES',
]
